### PR TITLE
Peek search

### PR DESCRIPTION
**Pull request by jafin**
Relates to #36.  Note: this does sit onto of a angular 1.4 branch I haven't full tested.  But you should be able to cherry pick out just the peeksearch bit easy enough.

### CODE REVIEW

**Comment by lukeschafer** [comment]
nice one finchy :)

Looks like you're making progress towards the very first issue: #1

**Comment by drewfreyling** [comment]
@jafin there is too much going on here in this PR. Please submit just the peak search as a PR. PRs should be small (where possible) and contain only one feature.

**Comment by jafin** [comment]
@drewfreyling Yeah sorry i added it to my 1.4 branch, I'll see if I can isolate it.

**Comment by jafin** [comment]
isolated branch up.

**Pull request closed without merging**
